### ISSUE TITLE
Test meta

### ISSUE THREAD

**Issue by akond** [johncowie/smidjen#1]
In midje I can assign meta to facts:
`(facts :slow ...)`, which is very good for filtering slow test during development.
How can I do the same with smidjen?

**Comment by johncowie** [comment]
This is not something that smidjen currently supports.  To be honest it's been a couple of years since I've looked at this library so I'm refreshing my memory :p

Smidjen adopts a *very* pared down feature-set of midje (which is partly a design goal), so it's really only the basics, but it compiles down to clojure.test, so it's also constrained by what clojure.test supports.  It looks like this would be possible (I think you can write ```(deftest ^:slow etc...)``` in clojure.test, so this shouldn't be too hard to do, and I also agree that it would be a nice thing.  Would need to double check that it's also supported in cljs.

Are you using smidjen in your projects?  I haven't been actively maintaining this for a while, but I'd happily review/accept pull-requests for this, or give you a hand implementing this feature if you're not sure how.

**Comment by akond** [comment]
I like the test presentation midje presents, but lein-midje has been a constant letdown, so I switched to lein-test-refresh, which is much more stable. But they are incompatible in regard to how they handle keywords. This is why I'm trying smidjen.

I think I'm going to try to implement this feature.

**Comment by akond** [comment]
It's strange stuff. Clojars [has been updated](https://clojars.org/smidjen/versions/0.2.3), but this repo does not have any references to [the underlying commit](https://github.com/johncowie/smidjen/commit/9fce3bdea1da26817c761b6ebccfa58c47bdb9b3). How could that be?

And project.clj still has version 0.2.0

**Comment by johncowie** [comment]
Ah that was my fault.  I made the changes to the project.clj to push to clojars, but then forgot to push that change to github.  Have fixed it now.  It's been a while since I've pushed something to clojars.. :-p

**Comment by akond** [comment]
Now it is vice versa.
The project.cljs contains 0.2.4, but there is no 0.2.4 version at the clojars.

**Comment by johncowie** [comment]
That's the snapshot version - 0.2.3 is on clojars, so no more commits will
be going into that release, hence the version is bumped.

**Comment by akond** [comment]
Oh, I see. Everything is alright then.
